export enum Tech {
  JAVA = "Java",
  JAVASCRIPT = "Javascript",
  TYPESCRIPT = "Typescript",
  GO = "Go",
  PYTHON = "Python",
  SPRING_BOOT = "Spring Boot",
  REACT_JS = "React.js",
  NEXT_JS = "Next.js",
  EXPRESS_JS = "Express.js",
  NODE_JS = "Node.js",
  GIT = "Git",
  DOCKER = "Docker",
  TENSORFLOW = "TensorFlow",
  WEB_RTC = "WebRTC",
  TAIL_WIND_CSS = "TailwindCSS",
  FLASK = "Flask",
}

export const techs = [
  Tech.JAVA,
  Tech.JAVASCRIPT,
  Tech.TYPESCRIPT,
  Tech.GO,
  Tech.PYTHON,
  Tech.SPRING_BOOT,
  Tech.REACT_JS,
  Tech.NEXT_JS,
  Tech.EXPRESS_JS,
  Tech.NODE_JS,
  Tech.GIT,
  Tech.DOCKER,
];
